[tool.poetry]
name = "server"
version = "0.1.0"
description = ""
authors=["Joe Boylson"]

[tool.poetry.dependencies]
python = "^3.9"
Flask = "^2.0.2"
waitress = "^3.0.0"
solidpython2 = "^2.1.0"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"